version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      DB_HOST: db # don't change this line
    depends_on:
      - db

  db:
    image: mysql:8.1
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: true
      MYSQL_DATABASE: usersDB
    volumes:
      - "./sql/init.sql:/docker-entrypoint-initdb.d/init.sql"
    ports:
      - "3306:3306"
